### ISSUE TITLE
Using interface name does not work with dynamic bridging

### ISSUE THREAD

**Issue by AshleyLai** [cplane-networks/dvnd-juju#7]
In neutron-openvswitch-cplane charm, the mgmt-int and data-interface config options expect a network interface name.  This is an issue with juju version juju-2.1-rc1 as it creates the bridge dynamically.  The network bridge is created when there is a container.

When I specify br-eth0 it complaints that br-eth0 does not exist.  However if I specify eth0 it failed with the following error.

tron-openvswitch-cplane/1-install-6602002006149998979"; dir "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm"
2017-01-25 15:18:37 INFO install Traceback (most recent call last):
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/install", line 139, in <module>
2017-01-25 15:18:37 INFO install     main()
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/install", line 133, in main
2017-01-25 15:18:37 INFO install     hooks.execute(sys.argv)
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/charmhelpers/core/hookenv.py", line 715, in execute
2017-01-25 15:18:37 INFO install     self._hooks[hook_name]()
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/install", line 123, in install
2017-01-25 15:18:37 INFO install     gw=config('data-gateway'))
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/cplane_network.py", line 59, in add_bridge
2017-01-25 15:18:37 INFO install     data = get_int_config(interface)
2017-01-25 15:18:37 INFO install   File "/var/lib/juju/agents/unit-neutron-openvswitch-cplane-1/charm/hooks/cplane_network.py", line 108, in get_int_config
2017-01-25 15:18:37 INFO install     raise InterfaceConfigurationException(msg)
2017-01-25 15:18:37 INFO install cplane_network.InterfaceConfigurationException: Interface eth0 does not have an address in the address family 2
2017-01-25 15:18:37 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by AshleyLai** [comment]
cplane-controller charm also uses interface name for multicast-intf and multicast-srv-intf.

**Comment by john-cplanenetworks** [comment]
Hi Ashley,

This sounds like a compatibility problem with RC1.    The behavior of a system should not change in a . (dot) release.    I will defer to David on how to handle this.

I suggest you try it with the verified release version of juju.   I believe the customer (PCCW) is using juju 2.0.


John Casey
CPlane Networks
Direct: 415-215-0854

**Comment by john-cplanenetworks** [comment]
Hi Ashley,

 

If you are using the MAAS then the best option is to renamed the interfaces of the nodes in the MAAS GUI to eth0 and eth1. This is what we did in our setup.

 

Thanks

Amar

 

From: John Casey [mailto:john@cplanenetworks.com] 
Sent: Thursday, January 26, 2017 2:07 AM
To: cplane-networks/dvnd-juju; cplane-networks/dvnd-juju
Cc: Subscribed; David Ames; Amarendra; Narinder Gupta
Subject: RE: [cplane-networks/dvnd-juju] Using interface name does not work with dynamic bridging (#7)

 

Hi Ashley,

 

This sounds like a compatibility problem with RC1.    The behavior of a system should not change in a . (dot) release.    I will defer to David on how to handle this.    

 

I suggest you try it with the verified release version of juju.   I believe the customer (PCCW) is using juju 2.0.  

 

 

John Casey

CPlane Networks

Direct: 415-215-0854
